### ISSUE TITLE
error while deploying

### ISSUE THREAD

**Issue by vijay1281991** [alexa/skill-sample-nodejs-audio-player#109]
Im getting error when in run ask deploy command : 
Request to the alexa skill management API fail

please help in this regards

**Comment by sebsto** [comment]
Hello,

Sorry to hear you're having issues  with this code sample. 
Which skill are you trying to deploy ?  Multiple Stream or Single Stream ?
Can you copy paste the command you;re typing and the full output of the deploy command ?  
You can use the ``--debug`` command line option to receive more details from the ``ask deploy`` command.  Thanks

**Comment by PiR1** [comment]
I have the same issue when i want to deploy the Single Stream
Debug mode:

 ```
C:\Users\pird\AppData\Roaming\npm\node_modules\ask-cli\lib\utils\logger-utility.js:37

                console.warn('[' + item.time + '] - ' + LEVEL_MAPPING[item.level] + ' - ' + item.activity.toUpperCase());
                                                                                                          ^

TypeError: Cannot read property 'toUpperCase' of undefined
    at displayLogs (C:\Users\pird\AppData\Roaming\npm\node_modules\ask-cli\lib\utils\logger-utility.js:37:107)
    at process.on (C:\Users\pird\AppData\Roaming\npm\node_modules\ask-cli\lib\utils\logger-utility.js:61:13)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.exit (internal/process.js:157:15)
    at Request.request [as _callback] (C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\lib\api\request-wrapper.js:45:25)
    at self.callback (C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
```

**Comment by PiR1** [comment]
I have the same issue when i want to deploy the single stream
Debug mode:
```
C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\lib\utils\logger-utility.js:37
                console.warn('[' + item.time + '] - ' + LEVEL_MAPPING[item.level] + ' - ' + item.activity.toUpperCase());
                                                                                                          ^

TypeError: Cannot read property 'toUpperCase' of undefined
    at displayLogs (C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\lib\utils\logger-utility.js:37:107)
    at process.on (C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\lib\utils\logger-utility.js:61:13)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.exit (internal/process.js:157:15)
    at Request.request [as _callback] (C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\lib\api\request-wrapper.js:45:25)
    at self.callback (C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
```

**Comment by sebsto** [comment]
This looks an error in one of the module dependencies for the ASK-CLI itself.  
Can you check you are using a recent version of Node and NPM and, if not, to upgrade to the latest.
Mines are 

> $ node --version
> v10.4.1
> $ npm --version
> 6.1.0

**Comment by PiR1** [comment]
I update Node, for npm it was ok.
But I have the same issue

**Comment by sebsto** [comment]
Which version of ask-cli are you using ?  Latest is 1.3.3
```
$ ask --version
1.3.3
```

To update :
`$ npm i -g ask-cli`

**Comment by PiR1** [comment]
i was in 1.3.1
I update it but it doesn't change
It gives me a skill id
`Response body: {"skillId":"amzn1.ask.skill.11b42d60-663c-486f-b055-e21c97375ea7"}`

But after i have the same issue

**Comment by sebsto** [comment]
The error seems to be in a library used by ask-cli.  
`C:\Users\user\AppData\Roaming\npm\node_modules\ask-cli\lib\utils\logger-utility.js:37`

I am running out of ideas here, unless suggesting to remove entirely that directory, and re-install again.
`C:\Users\user\AppData\Roaming\npm\node_modules`

Can I suggest also to post the question on the ASK-CLI support forum ?
https://forums.developer.amazon.com/spaces/165/index.html 

I am closing this issue as this is not an issue related to the Audio Skill Sample published in this repository.
