### ISSUE TITLE
Tests failing - Maxi80 : Skill Disabled - AssertionError: Target cannot be null or undefined

### ISSUE THREAD

**Issue by benappware** [alexa/skill-sample-nodejs-audio-player#110]
Hi there,
I'm new to Alex Skills so forgive my ignorance!  Also thanks for a create set of resources and nice documentation!!

I'm trying to create a single stream audio player and have got as far as running the tests with 
`(cd lambda && npm test)`

But I'm stuck on these test failures:
```
******************* REQUEST  **********************
{
  "version": "1.0",
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.123"
      },
      "user": {
        "userId": "amzn1.ask.account.123"
      },
      "apiEndpoint": "https://api.eu.amazonalexa.com",
      "apiAccessToken": "ey...g"
    }
  },
  "request": {
    "type": "AlexaSkillEvent.SkillDisabled",
    "requestId": "5f6ffb3d-0248-4ee3-83b2-8bf35c2106b7",
    "timestamp": "2018-04-19T16:13:01Z",
    "eventCreationTime": "2018-04-19T16:13:01Z",
    "eventPublishingTime": "2018-04-19T16:13:02Z"
  }
}
{}
    1) it responses with valid response structure
    2) it responses with no output speech
    3) it responses with no directive

  Maxi80 : Skill Disabled

******************* REQUEST  **********************
{
  "version": "1.0",
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.123"
      },
      "user": {
        "userId": "amzn1.ask.account.123"
      },
      "apiEndpoint": "https://api.eu.amazonalexa.com",
      "apiAccessToken": "ey...AQ"
    }
  },
  "request": {
    "type": "AlexaSkillEvent.SkillEnabled",
    "requestId": "b4de2803-bf0f-4ac5-b3f6-d9eac1c983ca",
    "timestamp": "2018-04-19T16:22:02Z",
    "eventCreationTime": "2018-04-19T16:22:02Z",
    "eventPublishingTime": "2018-04-19T16:22:34Z"
  }
}
{}
    4) it responses with valid response structure
    5) it responses with no output speech
    6) it responses with no directive


  46 passing (1s)
  6 failing

  1) Maxi80 : Skill Disabled
       it responses with valid response structure :
     AssertionError: Target cannot be null or undefined.
      at Assertion.checkResponseStructure (test/utils/Assertion.ts:9:34)
      at Context.it (test/test_skill_disabled.ts:41:7)

  2) Maxi80 : Skill Disabled
       it responses with no output speech :
     AssertionError: Target cannot be null or undefined.
      at Context.it (test/test_skill_disabled.ts:48:36)

  3) Maxi80 : Skill Disabled
       it responses with no directive :
     TypeError: Cannot read property 'response' of undefined
      at Context.it (test/test_skill_disabled.ts:57:27)

  4) Maxi80 : Skill Disabled
       it responses with valid response structure :
     AssertionError: Target cannot be null or undefined.
      at Assertion.checkResponseStructure (test/utils/Assertion.ts:9:34)
      at Context.it (test/test_skill_enabled.ts:41:7)

  5) Maxi80 : Skill Disabled
       it responses with no output speech :
     AssertionError: Target cannot be null or undefined.
      at Context.it (test/test_skill_enabled.ts:48:36)

  6) Maxi80 : Skill Disabled
       it responses with no directive :
     TypeError: Cannot read property 'response' of undefined
      at Context.it (test/test_skill_enabled.ts:57:27)
```
Why might the response be undefined in these cases please?

Many thanks in advance!

**Comment by sebsto** [comment]
Hello,  

Sorry to hear you're having issues with this code sample.  The above error usually means the skill can not execute and does not process the request at all.  It just returns a null/empry response, hence the test is failing.

I can replicate this error.  I will search for the cause and will let you know

Thank you

**Comment by sebsto** [comment]
This commit should fix the issue.  Let me know if this works
https://github.com/alexa/skill-sample-nodejs-audio-player/commit/3d0fb0b9542eae84ec066950bc345a519b4bf2aa
