### ISSUE TITLE
Problem with the skills response

### ISSUE THREAD

**Issue by smashedbotatos** [alexa/skill-sample-nodejs-audio-player#130]
No matter how I try to set the endpoint up it fails. The following is my CloudWatch error. There is not dist folder, and I tried src/index.handler with the same result. Am I doing something wrong?

Unable to import module 'dist/index': Error
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)

**Comment by smashedbotatos** [comment]
After going over the README, I missed a crucial step. which was running tsc to compile the typescript files.
