### ISSUE TITLE
errorMessage: cannot read property "userId"

### ISSUE THREAD

**Issue by akirac94** [alexa/skill-sample-nodejs-audio-player#8]
I'm getting this error when testing my lambda function:

START RequestId: a4e870f4-746e-11e6-a6c3-c93c5acb7cff Version: $LATEST
2016-09-06T20:15:24.359Z    a4e870f4-746e-11e6-a6c3-c93c5acb7cff    TypeError: Cannot read property 'userId' of undefined
    at Object.module.exports.:saveState.forceSave (/var/task/node_modules/alexa-sdk/lib/response.js:118:49)
    at emitNone (events.js:67:13)
    at AlexaRequestEmitter.emit (events.js:166:7)
    at Object.module.exports.:responseReady (/var/task/node_modules/alexa-sdk/lib/response.js:98:29)
    at emitNone (events.js:67:13)
    at AlexaRequestEmitter.emit (events.js:166:7)
    at Object.module.exports.:tell (/var/task/node_modules/alexa-sdk/lib/response.js:16:18)
    at emitOne (events.js:77:13)
    at AlexaRequestEmitter.emit (events.js:169:7)
    at exports.handler (/var/task/index.js:22:15)
END RequestId: a4e870f4-746e-11e6-a6c3-c93c5acb7cff
REPORT RequestId: a4e870f4-746e-11e6-a6c3-c93c5acb7cff  Duration: 80.64 ms  Billed Duration: 100 ms     Memory Size: 128 MB Max Memory Used: 25 MB  
Process exited before completing request

Is anyone else having this issue?

**Comment by rtrigoso** [comment]
Check your test on the lambda management console. Do you have a userId object as a property of the request array? and if you do, is it setup with a value?

You might be using a unfitting test to check your function.

**Comment by retrostrobe** [comment]
I'm getting the same error and have no idea on progressing further. I've followed each step of the tutorial as per the write up, but still the same error message.

> 2016-11-07T08:55:19.368Z  e879c3cd-a4c7-11e6-a084-8bdade499d04    TypeError: Cannot read property 'userId' of undefined
> at Object.module.exports.:saveState.forceSave (/var/task/node_modules/alexa-sdk/lib/response.js:118:49)
> at emitNone (events.js:67:13)
> at AlexaRequestEmitter.emit (events.js:166:7)
> at Object.module.exports.:responseReady (/var/task/node_modules/alexa-sdk/lib/response.js:98:29)
> at emitNone (events.js:67:13)
> at AlexaRequestEmitter.emit (events.js:166:7)
> at Object.module.exports.:tell (/var/task/node_modules/alexa-sdk/lib/response.js:16:18)
> at emitOne (events.js:77:13)
> at AlexaRequestEmitter.emit (events.js:169:7)
> at exports.handler (/var/task/index.js:22:15)

**Comment by retrostrobe** [comment]
Any idea on how to fix this @deegles? I'm not sure how to progress with this example anymore.
