### ISSUE TITLE
There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by vijay1281991** [alexa/skill-sample-nodejs-audio-player#99]
hi

I am new to alexa skill development
i followed the steps to create a audio player skills but im getting the following response "There was a problem with the requested skill's response" 
Here is the error log for lambda function. Please help to fix this issue

Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/index.js:3:13)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by MartinParis** [comment]
You need to know which error, is there something about that in your cloudwatch log?

**Comment by vijay1281991** [comment]
This is the details i see in log file.
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/index.js:3:13)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by vijay1281991** [comment]
where do i need to add .ask and skill.json file

**Comment by MartinParis** [comment]
You should use the directory structure as it is here on the site within the single and multiple stream directories.

**Comment by vijay1281991** [comment]
Thanks for the reply.
i followed the steps in readme.txt
 but im getting the error : "request to skill endpoint resulted in error"

**Comment by MartinParis** [comment]
You are not making much sense :-).
When and where do you get the error?

**Comment by vijay1281991** [comment]
Hi
I successfully deployed the code and it was working fine.
I tried changing the audio link in audio assets to play music from s3 bucket but the audio is not playing.
What is the required audio format to play in alexa?

**Comment by MartinParis** [comment]
You need to know why it is not playing. You can check your cloudwatch logs for that, it will show the reason. Could be authorization (you can check this with pasting the link in a browser and see what happens, or check your cloudwatch logs). Same for format.

**Comment by cooldevil007** [comment]
I also got this issue when try to build it in my system. I checked the cloudwatch too and got the same error.
Unable to import module 'index': Error
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/index.js:1:77)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)

**Comment by sebsto** [comment]
As the code in the "single stream" sample is based on TypeScript, you need to tell Lambda about the actual entry point into your code.  Did you follow this instruction from the README?

> IMPORTANT : ask CLI will create an index.handler lambda entry point by default. This projects uses typescript and the executable sources are now in the lambda/dist directory, so it is important to update the Lambda function configuration with the correct code entry point. You can do this using the AWS command line :
> 
> aws lambda update-function-configuration --function-name ask-custom-My_Radio-default --handler dist/index.handler --runtime nodejs8.10

**Comment by iandbanks** [comment]
I had this issue as well. The problem is that when the skill gets set up, it creates a new user role. That Role needs to be granted access to DynamoDB. So if you head to your AWS console > IAM > Roles > [role name]

In my case the role name was *ask-lambda-Multi-Stream-Audio-Player*

From there attach a Dynamo DB policy. I also found that I needed to up the Lambda policy to have more access, but that may have just been me.

<img width="2378" alt="iam_management_console" src="https://user-images.githubusercontent.com/1829348/45240754-62b74900-b2af-11e8-88f8-8d15b6aea5d9.png">

**Comment by avrpayyyur** [comment]
pls make sure your are zipping all the contents inside the lambda folder.
Dont zip the lambda folder, select the all content inside the lambda folder and zip

**Comment by ranjithavav** [comment]
> I also got this issue when try to build it in my system. I checked the cloudwatch too and got the same error.
> Unable to import module 'index': Error
> at Function.Module._load (module.js:474:25)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)
> at Object. (/var/task/index.js:1:77)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)

pls make sure your are zipping all the contents inside the lambda folder.
Dont zip the lambda folder, select the all content inside the lambda folder and zip

**Comment by PMR1158** [comment]
I had a similar issue. Turns out the handler text box under function code on AWS lambda management console was set to index.handler instead of src/index.handler. I changed the text, clicked save and it worked. Not sure if that's the problem but might be worth a look...

**Comment by samuelkilada** [comment]
You need to navigate into the lambda folder and run "tsc" to build the typescript files (one possible reason).

**Comment by aszk** [comment]
Does anyone still have the same issue?

**Comment by aszk** [comment]
Closing due to inactivity.
